// 資料來源：cubedex (https://github.com/poliva/cubedex) src/data/defaultAlgs.json
// Copyright (c) 2024 Pau Oliva Fora, MIT License。已移除括號並把 U'2 等寫法正規化。

export const OLL_ALGS: readonly [name: string, alg: string][] = [
  ["OLL-2 Zamboni", "F R U R' U' S R U R' U' f'"],
  ["OLL-3 Anti Nazi", "f R U R' U' f' U' F R U R' U' F'"],
  ["OLL-4 Nazi", "f R U R' U' f' U F R U R' U' F'"],
  ["OLL-17 Slash", "R U R' U R' F R F' U2' R' F R F'"],
  ["OLL-1 Blank", "R U2' R2' F R F' U2' R' F R F'"],
  ["OLL-18 Crown", "R U2' R2' F R F' U2' M' U R U' r'"],
  ["OLL-19 Bunny", "M U R U R' U' M' R' F R F'"],
  ["OLL-20 X", "M U R U R' U' M2' U R U' r'"],
  ["OLL-45 T / Suit Up", "F R U R' U' F'"],
  ["OLL-33 Key / Shoelaces", "R U R' U' R' F R F'"],
  ["OLL-6 Righty Square", "r U2' R' U' R U' r'"],
  ["OLL-5 Lefty Square", "r' U2 R U R' U r"],
  ["OLL-28 Arrow", "r U R' U' M U R U' R'"],
  ["OLL-57 H", "R U R' U' M' U R U' r'"],
  ["OLL-27 Sune", "R U R' U R U2' R'"],
  ["OLL-26 Anti Sune", "R U2' R' U' R U' R'"],
  ["OLL-21 H / Cross", "R U R' U R U' R' U R U2' R'"],
  ["OLL-22 Pi / Bruno", "R U2 R2 U' R2 U' R2 U2 R"],
  ["OLL-23 U / Headlights", "R2 D R' U2 R D' R' U2 R'"],
  ["OLL-24 T / Chameleon", "r U R' U' r' F R F'"],
  ["OLL-25 L / Bowtie", "F' r U R' U' r' F R"],
  ["OLL-7 Lightning", "r U R' U R U2' r'"],
  ["OLL-8 Reverse Lightning", "r' U' R U' R' U2' r"],
  ["OLL-11 Downstairs", "S R U R' U R U2' R' U2' S'"],
  ["OLL-12 Upstairs", "S R' U' R U' R' U2' R U2' S'"],
  ["OLL-40 Big Lightning / Anti Fung", "R' F R U R' U' F' U R"],
  ["OLL-39 Lefty Big Lightning / Fung", "L F' L' U' L U F U' L'"],
  ["OLL-44 P", "f R U R' U' f'"],
  ["OLL-43 Anti P", "f' L' U' L U f"],
  ["OLL-31 Couch", "R' U' F U R U' R' F' R"],
  ["OLL-32 Anti Couch", "S R U R' U' R' F R f'"],
  ["OLL-46 Seein' Headlights", "R' U' R' F R F' U R"],
  ["OLL-34 City", "R U R' U' B' R' F R F' B"],
  ["OLL-38 Mario", "R U R' U R U' R' U' R' F R F'"],
  ["OLL-36 Warrio", "L' U' L U' L' U L U L F' L' F"],
  ["OLL-51 Ant / Bottlecap", "F U R U' R' U R U' R' F'"],
  ["OLL-52 Rice Cooker", "R' F' U' F U' R U R' U R"],
  ["OLL-56 Street Lights", "F R U R' U' F' r U R' U' r' F R F'"],
  ["OLL-55 Highway", "R' F U R U' R2 F' R2' U R' U' R"],
  ["OLL-37 Mounted Fish", "F R U' R' U' R U R' F'"],
  ["OLL-35 Fish Salad", "R U2' R' R' F R F' R U2' R'"],
  ["OLL-10 Anti Kite", "R U R' U R' F R F' R U2' R'"],
  ["OLL-9 Kite", "R U R' U' R' F R2 U R' U' F'"],
  ["OLL-48 Breakneck", "f U R U' R' U R U' R' f'"],
  ["OLL-47 Anti Breakneck", "F' L' U' L U L' U' L U F"],
  ["OLL-53 Frying Pan", "r' U' R U' R' U R U' R' U2 r"],
  ["OLL-54 Anti Frying Pan", "r U R' U R U' R' U R U2' r'"],
  ["OLL-50 Front Squeezy", "r' U r2 U' r2' U' r2 U r'"],
  ["OLL-49 Back Squeezy", "r U' r2' U r2 U r2' U' r"],
  ["OLL-15 Squeegee", "R' F' R L' U' L U R' F R"],
  ["OLL-16 Anti Squeegee", "r U r' R U R' U' r U' r'"],
  ["OLL-13 Gun", "F U R U2' R' U' R U R' F'"],
  ["OLL-14 Anti Gun", "R' F R U R' F' R F U' F'"],
  ["OLL-41 Poodle", "R U R' U R U2' R' F R U R' U' F'"],
  ["OLL-42 Anti Poodle", "F S' R U R' U' F' U S"],
  ["OLL-29 WTF", "S' R U R' U' R' F R F' U S"],
  ["OLL-30 Anti WTF", "F U R U2' R' U' R U2' R' U' F'"],
]

export const PLL_ALGS: readonly [name: string, alg: string][] = [
  ["T Perm", "R U R' U' R' F R2 U' R' U' R U R' F'"],
  ["Aa Perm", "x R' U R' D2 R U' R' D2 R2 x'"],
  ["Ab Perm", "x R2 D2 R U R' D2 R U' R x'"],
  ["Ja Perm", "R' U L' U2 R U' R' U2 R L"],
  ["Jb Perm", "R U R' F' R U R' U' R' F R2 U' R'"],
  ["F Perm", "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"],
  ["Ra Perm", "R U' R' U' R U R D R' U' R D' R' U2 R'"],
  ["Rb Perm", "R2' F R U R U' R' F' R U2' R' U2 R"],
  ["Ga Perm", "R2 U R' U R' U' R U' R2 D U' R' U R D'"],
  ["Gb Perm", "R' U' R U D' R2 U R' U R U' R U' R2' D"],
  ["Gc Perm", "R2' U' R U' R U R' U R2 U D' R U' R' D"],
  ["Gd Perm", "R U R' U' D R2 U' R U' R' U R' U R2 D'"],
  ["Y Perm", "F R U' R' U' R U R' F' R U R' U' R' F R F'"],
  ["E Perm", "x' R U' R' D R U R' D' R U R' D R U' R' D' x"],
  ["Na Perm", "F' R U R' U' R' F R2 F U' R' U' R U F' R'"],
  ["Nb Perm", "r' D' F r U' r' F' D r2 U r' U' r' F r F'"],
  ["V Perm", "R' U R U' R' f' U' R U2 R' U' R U' R' f R"],
  ["Ua Perm", "R U R' U R' U' R2 U' R' U R' U R"],
  ["Ub Perm", "R' U R' U' R' U' R' U R U R2"],
  ["H Perm", "M2 U' M2 U2' M2 U' M2"],
  ["Z Perm", "M' U' M2' U' M2' U' M' U2' M2'"],
]
